### ISSUE TITLE
plugin generator failing with missing dependency (object-hash@^2.0.1)

### ISSUE THREAD

**Issue by halcyondude** [vmware-tanzu/plugin-library-for-octant#28]
Howdy!  This is my first time hacking on Octant Plugins, I'm attempting to scaffold a new TypeScript Plugin.

I'm not super familiar with node / webpack (not an expert) - this could be something simple :)

```
~/gh/halcyondude/plugin-library-for-octant (main ✔) ᐅ brew install node                  
node 16.3.0 is installed but outdated
==> Upgrading node
  16.3.0 -> 16.5.0 

<spam/>
```

Node appears to have been upgraded successfully

```
~/gh/halcyondude/octant-plugin-hello-world (main ✘)✭ ᐅ node -v
v16.5.0
```

Installed the octant-plugin generator:

```
(⎈ |docker-desktop:default)~/gh/halcyondude/octant-plugin-hello-world (main ✔) ᐅ yo @project-octant/octant-plugin

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │   Welcome to the Octant  │
   `---------´   │     Plugin generator!    │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Your plugin name:  octant-plugin-hello-world
? Your plugin description:  Howdy World, This plugin will do roughly nothing.
? Octant plugin path:  /Users/myoung/.config/octant/plugins
   create package.json
   create src/octant-plugin-hello-world.ts
   create src/routes.ts
   create src/content.ts
   create webpack.config.js
   create tsconfig.json


I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm ERR! code ETARGET
npm ERR! notarget No matching version found for object-hash@^2.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myoung/.npm/_logs/2021-07-19T21_34_30_096Z-debug.log
```

Here's the verbose log:

```
3068 verbose type range
3069 verbose stack object-hash: No matching version found for object-hash@^2.0.1.
3069 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
3069 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
3069 verbose stack     at async Promise.all (index 18)
3069 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:914:5)
3069 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
3069 verbose stack     at async Promise.all (index 1)
3069 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
3069 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:150:5)
3070 verbose cwd /Users/myoung/gh/halcyondude/octant-plugin-hello-world
3071 verbose Darwin 20.5.0
3072 verbose argv "/usr/local/Cellar/node/16.5.0/bin/node" "/usr/local/bin/npm" "install" "--cache-min" "86400"
3073 verbose node v16.5.0
3074 verbose npm  v7.19.1
3075 error code ETARGET
3076 error notarget No matching version found for object-hash@^2.0.1.
3077 error notarget In most cases you or one of your dependencies are requesting
3077 error notarget a package version that doesn't exist.
3078 verbose exit 1
```

**Comment by halcyondude** [comment]
running `npm install` works (no other changes made)

```
~/gh/halcyondude/octant-plugin-hello-world (main ✘)✚ ᐅ npm install                                           
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 799 packages, and audited 800 packages in 32s

32 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

**Comment by liamrathke** [comment]
Just tried replicating this on my local, and wasn't able to reproduce the `object-hash` error. Are you still running into this issue?

Here's my console output; I'm on macOS Big Sur 11.4:

```
lrathke@lrathke-a01 Desktop % yo
? 'Allo Liam! What would you like to do? Update your generators
? Generators to update @project-octant/generator-octant-plugin
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
I've just updated your generators. Remember, you can update
a specific generator with npm by running:

    npm install -g generator-_______
lrathke@lrathke-a01 Desktop % node -v
v16.5.0
lrathke@lrathke-a01 Desktop % mkdir test-plugin && cd test-plugin
lrathke@lrathke-a01 test-plugin % yo @project-octant/octant-plugin

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │   Welcome to the Octant  │
   `---------´   │     Plugin generator!    │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Your plugin name:  test-plugin
? Your plugin description:  test-plugin
? Octant plugin path:  /Users/lrathke/.config/octant/plugins
   create package.json
   create src/test-plugin.ts
   create src/routes.ts
   create src/content.ts
   create webpack.config.js
   create tsconfig.json


I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 799 packages, and audited 800 packages in 9s

32 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

Also, does the generated plugin work fine with Octant?
